services:
    php-apache-environment:
        image: dindakuis2
        container_name: php-apache
        depends_on:
            - db
        volumes:
            - ./dindakuis2/:/var/www/html/
        ports:
            - 8000:80
        networks:
            - backend
    db:
        container_name: mysql-db
        image: mysql
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: Admin123!
          MYSQL_DATABASE: ajc
        ports:
            - "3306:3306"
        volumes:
          - db:/var/lib/mysql
          - ./dindakuis2/ajc.sql:/docker-entrypoint-initdb.d/ajc.sql
        networks:
          - backend
volumes:
 db:
networks:
 backend:
  name: backend-network